### ISSUE TITLE
compilation errors due to ctx and fd being undeclared functions

### ISSUE THREAD

**Issue by zoe-vb** [lutoma/xelix#104]
Having build the toolchain and running make the build errors out and say: src/net/socket.c:194:49: error: 'ctx' undeclared (first use in this function)

**Comment by lutoma** [comment]
Hi there!

Yes, the networking code is currently broken as a result of some refactoring in other compoinents. I'll see if I can fix it in the coming days. For now, I recommend you compile with networking disabled (You can run `make menuconfig` to configure these things). it works fine then.

**Comment by zoe-vb** [comment]
Okay, thanks it does build this way

**Comment by lutoma** [comment]
Glad to hear that. I'm not sure how compatible the current kernel main branch is with the last image, so you might run into some incompatibilities there. If you're interested in playing a bit more with Xelix, I might release a new userland image soonish that should be more up  to date.
