### ISSUE TITLE
Commit "New build system for userland packages" has small error

### ISSUE THREAD

**Issue by ZanyXDev** [lutoma/xelix#87]
[After commit](https://github.com/lutoma/xelix/tree/0f0adf48a2f6107e7f5650629a805d293d299e30), the file https://github.com/lutoma/xelix/commits/master/land/binutils/xelix_i386.sh  was renamed to [elf_i386_xelix.sh](https://github.com/lutoma/xelix/commits/master/land/binutils/elf_i386_xelix.sh), 
but in the [makefile](https://github.com/lutoma/xelix/blob/master/toolchain/Makefile#L35) used the old name, which leads to errors during assembly.

**Comment by ZanyXDev** [comment]
after rename xelix_i386.sh  to elf_i386_xelix.sh
>#configure
>#make -C toolchain 
># error `make[5]: *** No rule to make target 'eelf_i386_xelix.o', needed by 'ld-new'.  Stop.`
`make  all-recursive
make[4]: Entering directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld'
Making all in po
make[5]: Entering directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld/po'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld/po'
make[5]: Entering directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld'
gcc -DHAVE_CONFIG_H -I. -I../../../download/binutils-2.31.1/ld  -I. -I../../../download/binutils-2.31.1/ld -I../bfd -I../../../download/binutils-2.31.1/ld/../bfd -I../../../download/binutils-2.31.1/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/home/zanyxdev/github/C/xelix/toolchain/local/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -MT ldmain.o -MD -MP -MF .deps/ldmain.Tpo -c -o ldmain.o \
  -DDEFAULT_EMULATION='"elf_i386_xelix"' \
  -DBINDIR='"/home/zanyxdev/github/C/xelix/toolchain/local/bin"' -DTOOLBINDIR='"/home/zanyxdev/github/C/xelix/toolchain/local/i786-pc-xelix/bin"' \
  -DTARGET='"i786-pc-xelix"' -DTARGET_SYSTEM_ROOT=\"\" \
  ../../../download/binutils-2.31.1/ld/ldmain.c
mv -f .deps/ldmain.Tpo .deps/ldmain.Po
gcc -DHAVE_CONFIG_H -I. -I../../../download/binutils-2.31.1/ld  -I. -I../../../download/binutils-2.31.1/ld -I../bfd -I../../../download/binutils-2.31.1/ld/../bfd -I../../../download/binutils-2.31.1/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/home/zanyxdev/github/C/xelix/toolchain/local/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -MT ldemul.o -MD -MP -MF .deps/ldemul.Tpo -c -o ldemul.o ../../../download/binutils-2.31.1/ld/ldemul.c
mv -f .deps/ldemul.Tpo .deps/ldemul.Po
gcc -DHAVE_CONFIG_H -I. -I../../../download/binutils-2.31.1/ld  -I. -I../../../download/binutils-2.31.1/ld -I../bfd -I../../../download/binutils-2.31.1/ld/../bfd -I../../../download/binutils-2.31.1/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/home/zanyxdev/github/C/xelix/toolchain/local/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -MT ldfile.o -MD -MP -MF .deps/ldfile.Tpo -c -o ldfile.o \
-DSCRIPTDIR='"/home/zanyxdev/github/C/xelix/toolchain/local/i786-pc-xelix/lib"' -DBINDIR='"/home/zanyxdev/github/C/xelix/toolchain/local/bin"' -DTOOLBINDIR='"/home/zanyxdev/github/C/xelix/toolchain/local/i786-pc-xelix/bin"' \
 ../../../download/binutils-2.31.1/ld/ldfile.c
mv -f .deps/ldfile.Tpo .deps/ldfile.Po
make[5]: *** No rule to make target 'eelf_i386_xelix.o', needed by 'ld-new'.  Stop.
make[5]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld'
make[4]: *** [Makefile:1764: all-recursive] Error 1
make[4]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld'
make[3]: *** [Makefile:1047: all] Error 2
make[3]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils/ld'
make[2]: *** [Makefile:7137: all-ld] Error 2
make[2]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils'
make[1]: *** [Makefile:849: all] Error 2
make[1]: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain/build/binutils'
make: *** [Makefile:40: binutils-make] Error 2
make: Leaving directory '/home/zanyxdev/github/C/xelix/toolchain'
`

**Comment by lutoma** [comment]
Hi there! You're right, the toolchain build process is a bit buggy at the moment. I'm somewhat busy right now, but I'll see if I can fix it in the next days.

**Comment by lutoma** [comment]
Well, it took me way too long to get back to Xelix, but with the recent commits the toolchain build process should be working again if you want to give it another try.
